### PR TITLE
Allow any discord server to use command when testing

### PR DESCRIPTION
**Pull request by kennarddh**
Ignore server whitelist when using `t?` prefix

So no need to add each test discord server to guilds id whitelist

https://github.com/DogeMultiverse/watermelonbot/commit/72976111b77d765a29a73debdb25ef3e29b54481

This also split the `is_valid_guild` to other file to prevent circular import when using it in other file

### CODE REVIEW

**Comment by alexpvpmindustry** [comment]
Too many changes... Only commit the actual code parts... I can't check easily on my phone.

Also, I think the list of valid guilds should be inside the config, so every can set it to their own guild

**Comment by alexpvpmindustry** [comment]
173 additions

**Comment by kennarddh** [comment]
> Too many changes... Only commit the actual code parts... I can't check easily on my phone.
> 
> Also, I think the list of valid guilds should be inside the config, so anyone can set it to their own guild

yes

**Comment by kennarddh** [comment]
> 173 additions

its my auto format on save...

how do i disable it? pycharm? but now how to revert it....

**Comment by alexpvpmindustry** [comment]
Ask pycharm or google....
To revert, see the diff, and there should be a gui to revert individual
lines.

Or u can wait till later... I can change when I'm available

**Pull request merged**
